// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkmqmitvawjfolshgesu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbXFtaXR2YXdqZm9sc2hnZXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODEwNTIsImV4cCI6MjA2NjI1NzA1Mn0.jjC4bPQQI2nQkGWAZMMVbhsv-Mdeem0nDBac9Y1GvnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);